In [1]:
# Swapping two variables without using a third variable
a = 5
b = 10

# Swap the values
a, b = b, a

print("After swapping:")
print("a =", a)
print("b =", b)

After swapping:
a = 10
b = 5


In [7]:
def reverse_word_order(text):
    words = text.split()
    reversed_words = words[::-1]
    reversed_text = " ".join(reversed_words)
    return reversed_text


a = "this is my book"

result = reverse_word_order(a)
print(result)

book my is this


In [11]:
def reverse_order_string(text):
    text = text.split()
    reverser_order = text[::-1]
    return " ".join(reverser_order)


a = "this is my book"
print(reverse_order_string(a))  # Output: 'book my is this'

book my is this


In [29]:
b = "im a data Scientist"
print(b[8:4:-1])

atad


In [20]:
a = [i for i in range(11, 30) if i % 2 != 0]
print(a)

[11, 13, 15, 17, 19, 21, 23, 25, 27, 29]


In [26]:
import numpy as np

a = np.arange(9).reshape(3, 3)

a = np.expand_dims(a, axis=0)

print(a)

a.ndim

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


3

In [44]:
# names = ["Cecilia", "Lise", "Marie"]

# counts = [len(names) for name in names]
# longest_name = None

# max_count = 0


# for i, name in enumerate(names):
#     count = counts[i]

#     if count > max_count:
#         max_count = count

#         longest_name = name

# print(longest_name)

Cecilia


In [61]:
names = [
    "Ram Kumar",
    "Alice",
    "Bob",
    "Charlie",
    "David rusuomie",
    "Eve",
    "Frank",
    "Grace",
    "Henry",
    "Ivy",
]
# Create a dictionary with names as keys and their corresponding scores as values

counts = [len(names) for name in names]

max_count = 0

longest_name = None

for i, name in enumerate(names):
    count = counts[i]
    if count > max_count:
        max_count = count
        longest_name = name

print(longest_name)

Ram Kumar
